### ISSUE TITLE
Tables not being created

### ISSUE THREAD

**Issue by Silarn** [SaifurRahmanMohsin/Txt#1]
Just FYI, I'm using the newest RC release of October - just in case that changes anything.

I logged out and back in as mentioned in the installation instructions, but I still get table missing errors when I attempt to go to the configuration for the robots or people .txt pages.

**Comment by SaifurRahmanMohsin** [comment]
I am looking into it. I'm currently migrating the plugin to RC and will update it soon. Adding a seeder as well to populate agents automatically on install.

**Comment by Silarn** [comment]
I figured out what the problem is. I'm using table prefixes, but when querying the tables this is being ignored.

**Comment by Silarn** [comment]
No, I'm wrong. Sorry.

Strange, the tables are there. Is there a cache issue?

**Comment by Silarn** [comment]
I figured out what the problem is. I'm using table prefixes, but when querying the tables this is being ignored in one case:

models/robot/columns.yaml

This directive seems to be ignoring the table prefixes.

**Comment by Silarn** [comment]
I've made a short term solution my manually correcting the table names in the columns.yaml files, but obviously there needs to be a way to get the correct table name. Hard-coding the table names doesn't work when prefixes are used.

**Comment by Silarn** [comment]
One more thing which is another October change:

You have to change the Plugin.php registerFormWidges() definition from 'alias' to 'code'.

**Comment by Silarn** [comment]
models/human/columns.yaml needs an update, too.

And, I presume, contollers/Humans.php.

**Comment by SaifurRahmanMohsin** [comment]
Oh crud I failed to push that commit. Thanks

**Comment by SaifurRahmanMohsin** [comment]
@Silarn The issue appears to be resolved at my end but I've got a new duplicate issue related the this. Could you please check if your issue is indeed resolved and provide some feedback? Thanks
