### ISSUE TITLE
Page error in admin area

### ISSUE THREAD

**Issue by sliderweb** [SaifurRahmanMohsin/Txt#17]
Hello! I'm using this plugin so far, but after last updates i have en error in admin area on create any human or robot entry (/backend/mohsin/txt/{humans|robots}/create)

LOGS
exception 'October\Rain\Exception\SystemException' with message 'Unable to find configuration file @/plugins/mohsin/txt/models/directive/fields.yaml defined for Owl\FormWidgets\HasMany\Widget.' in /media/HD500/hosting/sliderweb/modules/system/traits/ConfigMaker.php:63

I've try to delete/reinstall/uninstall and clean install plugin - not help. Still PAGE ERROR
I don't know how to fix this

**Comment by abhi1693** [comment]
Even I'm getting the same error

**Comment by SaifurRahmanMohsin** [comment]
Kind of held up with excessive work so I wouldn’t be able to fix it ASAP. Give me a couple of days. Thanks for reporting this.

**Comment by SaifurRahmanMohsin** [comment]
This is same as issue #16 but unfortunately the owner of hasmany widget repo did not accept the PR for over half a year now. I have decided to add the widget as part of the plugin than a dependency in the next commit to resolve the issue.
