### ISSUE TITLE
Upgrade issue with existing databases

### ISSUE THREAD

**Issue by Silarn** [SaifurRahmanMohsin/Txt#3]
The current update added seed info for the Agents table --

Problem is, it doesn't check against any entries that might have already been added, so the updater crashed when it found my * entry that I had already added.

I got it to go through by manually deleting the * entry and setting the correct ID after it updated successfully.

I suppose this is only an issue for the few people that might have installed it before the current version, but nonetheless. :)

**Comment by SaifurRahmanMohsin** [comment]
Thanks

**Comment by Silarn** [comment]
This does prevent the error, but it's also going to overwrite any matching entries. In looking through the Laravel docs, it looks like that function calls another method which either finds a matching column or creates a new one.
```php
public static function firstOrCreate(array $attributes)
	{
		if ( ! is_null($instance = static::where($attributes)->first()))
		{
			return $instance;
		}
		return static::create($attributes);
	}
```
I think something along these lines would work.

```php
if ( is_null(Agent::where([ 'name' => $agent['name'] ])->first()) )
{
    Agent::create([ 'name' => $agent['name'] ])->fill([ 'comment' => $agent['comment'] ])->save();
}
```

**Comment by SaifurRahmanMohsin** [comment]
Thanks will include in the next commit along with some touch ups.

**Comment by Silarn** [comment]
I just thought about the problem, and I guess I'd have to run tests. 

In updateOrCreate, it uses the first table parameter to locate a row with the matching attributes and the second to write new values. So I see this working two ways. The comment may be different even if the agent is the same. So I don't think this is going to match existing rows with different comments and may or may not lead to the same initial problem. That being said, if it DOES match a row with the same agent - even if the comment was different, there were no values passed in so it would not overwrite that data.

I still think the modified code is a safer solution, either way.

**Comment by SaifurRahmanMohsin** [comment]
you could simply use firstOrCreate. That should solve the issue. There are other ways too. Don't worry I'll add this in the next commit. I am testing another feature to add to the plugin at the moment.
