### ISSUE TITLE
Correct value of attribution is not loaded when viewing Human.txt entry

### ISSUE THREAD

**Issue by justin-lau** [SaifurRahmanMohsin/Txt#5]
#### Bug summary
The previously saved value of attribution isn't loaded to the select input when an entry is viewed.

#### Request location
backend/mohsin/txt/humans/update

#### Reproduce steps
1. Create an Human.
2. Set the `Attribution` to anything but `Team`.
3. Save and Close.
4. Click on this newly created Entry.
5. Attribution is set to `Team`.

#### Expected result
Attribution should be loaded from database.

#### Actual result
Attribution is set to default value every time.

**Comment by SaifurRahmanMohsin** [comment]
Thanks for this concise bug report. My apologies for the insane delay. Will fix!
