### ISSUE TITLE
Sitemap link

### ISSUE THREAD

**Issue by vojtasvoboda** [SaifurRahmanMohsin/Txt#8]
Will be great to have possibility set sitemap.xml link to the end of robots.txt file.

http://www.sitemaps.org/protocol.html#submit_robots

**Comment by SaifurRahmanMohsin** [comment]
I have added this but it’s compatible with RainLab.Sitemap plugin so it adds the line only if that plugin is installed. Thanks for your suggestion. I hope you enjoy my plugin!

**Comment by vojtasvoboda** [comment]
I tested it and works well, thanks!
